### ISSUE TITLE
Missing methods when exporting `ipcRenderer` from the *preload*

### ISSUE THREAD

**Issue by codeit-ninja** [cawa-93/unplugin-auto-expose#6]
When I export the `ipcRenderer` from the *preload* script (I am using your template for Electron + Vite + TypeScript), why can't I use the `.on` methods. Only some methods are exported along with it.

![image](https://user-images.githubusercontent.com/22219122/196002521-214e4dfa-6772-47c6-853e-ffe70b388cf4.png)

**Comment by cawa-93** [comment]
See https://github.com/electron/electron/issues/21437
