### ISSUE TITLE
How can I build types of electron API and publish to npm?

### ISSUE THREAD

**Issue by dohooo** [cawa-93/unplugin-auto-expose#8]
THX for this awesome lib! BTW, Is there any way to export declaration of electron API and publish it to the npm?

**Comment by cawa-93** [comment]
Electron have build-in TypeScript declaration
https://www.runpkg.com/?electron@21.3.0/electron.d.ts

**Comment by dohooo** [comment]
Sry, I mean I want to expose `electronMethods` types.
```
contextBridge.exposeInMainWorld("__electron", electronMethods);
```

**Comment by cawa-93** [comment]
just like normal ts package, i think
```
tsc --declaration --emitDeclarationOnly
```
